version: '3'
services:

  kitchen:
    container_name: kitchen

    image: robinpas/kitchen:v0.0.3
    ports:
      - 8000:8000
    restart: always

  inventory:
    container_name: inventory

    image: robinpas/inventory:v0.0.3
    ports:
      - 8001:8001
    restart: always

  nginx:
    depends_on:
      - kitchen
      - inventory
    image: robinpas/nginx:v0.0.2
    ports:
      - 80:80
